### ISSUE TITLE
不要默认占用 "Alt+上箭头" 或 "Alt+下箭头" 快捷键

### ISSUE THREAD

**Issue by SlimeNull** [LemonCodeTeam/Lemon-App#13]
这在大多数编程软件中, 都是 "移动当前代码到上一行" 或 "移动当前代码到下一行" 的功能. 如果要占用, 也不应该作为全局热键注册.

然后, 全局热键建议作为可选项在设置页面中提供, 默认不开启. 因为用户想要知道"下一首"和"上一首" 的全局热键, 基本都是需要去设置页面看的, 为了避免在用户看之前受影响, 所以默认关闭. 当用户看到热键时, 如果和自己已有热键冲突, 也可以直接改掉.

**Comment by TwilightLemon** [comment]
感谢你的反馈  后续版本将改进
