### ISSUE TITLE
记录登录

### ISSUE THREAD

**Issue by cfaha** [LemonCodeTeam/Lemon-App#6]
可以保存登录信息，下次打开软件自动登录嘛

**Comment by TwilightLemon** [comment]
有这个功能的  但由于某些原因保存配置文件时时常出现错误。这个问题我也遇到很久了，是出在Settings.SaveSettings上，在程序通过托盘退出时调用(似乎不是很好)。我计划未来几天内解决这个问题(maybe)

**Comment by TwilightLemon** [comment]
问题已经解决 是无法读取登录id的问题 
https://github.com/LemonCodeTeam/Lemon-App/commit/5ff0a0e74fe2ffaed5a4e22807696fbdfc9f4225
