### ISSUE TITLE
是如何获取到请求API的？

### ISSUE THREAD

**Issue by YuJian920** [LemonCodeTeam/Lemon-App#9]
例如登录功能的实现，我没有系统的学过C#，看代码压根看不明白，想问问是怎么获取到相对应的API的

**Comment by TwilightLemon** [comment]
Hey，很抱歉这么晚才回复你，因为我正在备战高考，几乎没有时间关注了。你可以加我QQ，6月中下旬的时候再交流。感谢支持！

**Comment by YuJian920** [comment]
OK
